force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAND{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Full_Name__c.field-meta.xml
<CustomField>
    <fullName>Full_Name__c</fullName>
    <label>Name</label>
    <length>75</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Job_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Job_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job_Requisition</label>
    <referenceTo>Job_Requisition__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Job_Requisition__c/Job_Requisition__c.object-meta.xml
<CustomObject>
    <label>Job_Requisition</label>
    <nameField>
        <displayFormat>JR-{0000}</displayFormat>
        <label>Job_Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/GetCandidatesForJobReq.cls
public with sharing class GetCandidatesForJobReq {
    
    
    public class Input{
        @InvocableVariable(label='Job Req Id' description='Id of the Job Requisition' required=true)
        public Id jobReqId;
    }
    
    public class Output{
        @InvocableVariable(label='Candidate Id')
        public Id candidateId;
        
        @InvocableVariable(label='Candidate Name')
        public String candidateName;
    }
    
    @InvocableMethod(label='Get candidate under Job Req' description='Returns all candidates associated with a given Job Requisition')
    public static List<Output> getCandidateForJobReq(List<Input> inputs){
        

        Set <Id> jobReqIds= new Set<Id>();
        for (Input inp: inputs){
            jobReqIds.add(inp.jobReqId);
        }

        List<Candidate__c> allCandidates = [
            SELECT Id, Full_Name__c, Job_Requisition__c
            FROM Candidate__c
            WHERE Job_Requisition__c IN :jobReqIds
        ];

        // 3. Group candidates by their Job Requisition Id, multiple candidate can have same JobReqID,one map, where each Job Requisition Id points to the full list of candidates under it
        Map<Id, List<Candidate__c>> candidatesByJobReq = new Map<Id, List<Candidate__c>>();
        for (Candidate__c c : allCandidates) {

            //creating a bucket for each unique Job req Id
            if (!candidatesByJobReq.containsKey(c.Job_Requisition__c)) {
                candidatesByJobReq.put(c.Job_Requisition__c, new List<Candidate__c>());
            }

            //candidatesByJobReq.get('001XXXXX')  →  returns [Alice]
            // .add(c)                              →  adds Bob to that list
            candidatesByJobReq.get(c.Job_Requisition__c).add(c);
        }


        List<Output> results = new List<Output>();
        for (Input inp : inputs) {
            List<Candidate__c> matchedCandidates = candidatesByJobReq.get(inp.jobReqId);
            if (matchedCandidates != null) {
                for (Candidate__c c : matchedCandidates) {
                    Output out = new Output();
                    out.candidateId = c.Id;
                    out.candidateName = c.Full_Name__c;
                    results.add(out);
                }
            }
        }

        return results;


    }
}