force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAND{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Job_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Job_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job_Requisition</label>
    <referenceTo>Job_Requisition__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Interview__c/Interview__c.object-meta.xml
<CustomObject>
    <label>Interview</label>
    <nameField>
        <displayFormat>INT{0000}</displayFormat>
        <label>Interview Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Interviews</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Interview__c/fields/Candidate__c.field-meta.xml
<CustomField>
    <fullName>Candidate__c</fullName>
    <label>Candidate</label>
    <referenceTo>Candidate__c</referenceTo>
    <relationshipLabel>Interviews</relationshipLabel>
    <relationshipName>Interviews</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Job_Requisition__c/Job_Requisition__c.object-meta.xml
<CustomObject>
    <label>Job_Requisition</label>
    <nameField>
        <displayFormat>JR-{0000}</displayFormat>
        <label>Job_Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CandidateTriggerHandlerTest.cls
@isTest
public class CandidateTriggerHandlerTest {

// Creates shared test data used by every @isTest method below. // Runs once automatically before each test method, with its own // isolated, auto-rolled-back copy of this data per test.

    @TestSetup
    static void setupTestData() { 

        Job_Requisition__c jobReq = new Job_Requisition__c(Title__c='Salesforce Developer', Department__c='Engineering',Status__c='Open');
        insert jobReq;

        Candidate__c cand = new Candidate__c(Email__c='test@gamail.com', Stage__c='Applied',Outcome__c='Pending', Phone__c='7309882920',Job_Requisition__c=jobReq.Id);
        insert cand;
    }


    @isTest
    static void testInterviewCreationOnStageChangeToInterview(){

        //This queries for the Candidate record created in @testSetup and testSetup already ran before this, so it will have the
        Candidate__c cand = [Select Id,Stage__c from Candidate__c Limit 1]; 
        
        
        Test.startTest();
        cand.Stage__c = 'Interview'; 
        update cand;                                       
        Test.stopTest();

        List<Interview__C> interview = [Select Id From Interview__c where Candidate__c =:cand.Id];
        system.assertEquals(1, interview.size(), 'Expected only one Interview Creation');

    }
}