force-app/main/default/objects/Candidate__c/Candidate__c.object-meta.xml
<CustomObject>
    <label>Candidate</label>
    <nameField>
        <displayFormat>CAND{0000}</displayFormat>
        <label>Candidate Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Candidates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Candidate__c/fields/Job_Requisition__c.field-meta.xml
<CustomField>
    <fullName>Job_Requisition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Job_Requisition</label>
    <referenceTo>Job_Requisition__c</referenceTo>
    <relationshipLabel>Candidates</relationshipLabel>
    <relationshipName>Candidates</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Outcome__c.field-meta.xml
<CustomField>
    <fullName>Outcome__c</fullName>
    <label>Outcome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Hired</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Parse_Status__c.field-meta.xml
<CustomField>
    <fullName>Parse_Status__c</fullName>
    <label>Parse Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Parsed_JSON__c.field-meta.xml
<CustomField>
    <fullName>Parsed_JSON__c</fullName>
    <description>This stores the raw API response for audit/debugging</description>
    <label>Parsed JSON</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Parsed_Skills__c.field-meta.xml
<CustomField>
    <fullName>Parsed_Skills__c</fullName>
    <label>Parsed Skills</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Candidate__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <label>Stage</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Screening</fullName>
            </value>
            <value>
                <fullName>Interview</fullName>
            </value>
            <value>
                <fullName>Offer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job_Requisition__c/Job_Requisition__c.object-meta.xml
<CustomObject>
    <label>Job_Requisition</label>
    <nameField>
        <displayFormat>JR-{0000}</displayFormat>
        <label>Job_Requisition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Job_Requisitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job_Requisition__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ResumeParseQueueableTest.cls
@isTest
private class ResumeParseQueueableTest {


    @TestSetup
    static void setupTestData(){
        Job_Requisition__c job_req = new Job_Requisition__c(Title__c = 'Test Role', Department__c = 'Test', Status__c = 'Open');
        insert job_req;
        Candidate__c cand = new Candidate__c( Email__c = 'test@example.com', Phone__c = '9999999999', Stage__c = 'Applied', Outcome__c = 'Pending', Job_Requisition__c = job_Req.Id ); 
        insert cand;
    }

    @isTest
    static void testResumeParsUpdatesCanidate() {
        Candidate__c cand = [Select Id from Candidate__c Limit 1];
        Test.startTest();
        System.enqueueJob(new ResumeParseQueueable(cand.Id));
        Test.stopTest();

        Candidate__c updateCandidate = [Select Id, Parsed_Skills__c,Parse_Status__c, Parsed_JSON__c from Candidate__c where Id =:cand.Id] ;
        System.assertEquals('Success', updateCandidate.Parse_Status__c, 'Result is not successful');
        System.assertEquals('Apex, LWC, Flows',updateCandidate.Parsed_Skills__c,'Skilled should be updated');
        System.assert(updateCandidate.Parsed_JSON__c!=Null, 'Expected Parsed_JSON to be populated');

    }
}