force-app/main/default/objects/Offer__c/Offer__c.object-meta.xml
<CustomObject>
    <label>Offer</label>
    <nameField>
        <displayFormat>OFR{0000}</displayFormat>
        <label>Offer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Offers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Offer__c/fields/Approved_By__c.field-meta.xml
<CustomField>
    <fullName>Approved_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approved By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Offers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Offer__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
                <default>true</default>
                <label>Draft</label>
            </value>
            <value>
                <fullName>Pending Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Sent</fullName>
            </value>
            <value>
                <fullName>Accepted</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OfferTriggerHandler.cls
public class OfferTriggerHandler extends TriggerHandler {
    protected override void afterUpdate(List<SObject> newList, Map<Id, SObject> newMap, Map<Id, SObject> oldMap) {
        
        List<Offer__c> newOffer = (List<Offer__c>)newList;
        Map<Id,Offer__c> oldOffersMap = (Map<Id,Offer__c>)oldMap;
        
        Set<Id> eligbleOffers = new Set<Id>();
        
        for(Offer__c off:newOffer){
            
            offer__c oldOffer = oldOffersMap.get(off.Id);
            if(off.Status__c== 'Approved' && oldOffer.Status__c != 'Approved'){
                eligbleOffers.add(off.Id);
            }
        }
        
        if (eligbleOffers.isEmpty()) {
            return;
        }
        
        Map<Id, Id> approverIdByOfferId = new Map<Id, Id>();
        
        for(ProcessInstanceStep step:[SELECT Id,ActorId,ProcessInstance.TargetObjectId from ProcessInstanceStep where StepStatus ='Approved' and ProcessInstance.TargetObjectId in :eligbleOffers]){
            
            approverIdByOfferId.put(step.ProcessInstance.TargetObjectId, step.ActorId);
            
        }
        
        List<Offer__c> offersToUpdate = new List<Offer__c>();
        for(Id eOffer: eligbleOffers){
            if(approverIdByOfferId.containsKey(eOffer)){
                Offer__c newOfferToadd = new Offer__c();
                newOfferToadd.Id = eOffer;
                newOfferToadd.Approved_By__c = approverIdByOfferId.get(eOffer);
                
                offersToUpdate.add(newOfferToadd);
            }
        }
        
        if(!offersToUpdate.isEmpty()){
            update offersToUpdate;
        }
        
    }
}